### ISSUE TITLE
extension-embedded CSS activates on non-math HTML

### ISSUE THREAD

**Issue by af4jm** [goessner/mdmath#107]
### Summary

Tables render differently in VSCode previews than they do on the web... tables are centered instead of left-aligned, borders change, etc., even in Markdown pages that have no math ML in them

### Expected behavior

HTML renders similarly in both places... CSS files that are part of this extension should only show up in dev tools for Math elements

### Actual behavior

this extension's CSS takes over all tables in all Markdown files

### Steps to reproduce

1. Open VSCode Markdown preview of a doc with a table (that's not inside a math block)
2. Inspect the table
3. See table CSS (with `!important`) altering the table layout

### Code example

any table, either Markdown or raw HTML in Markdown

### Related links

* [Markdown+Math](https://github.com/goessner/mdmath)

### Environment

```text
     Operating system: ___
       VSCode version: 1.52.1
Markdown+Math version: 2.5.1
```

**Comment by goessner** [comment]
Hmmm ... it is not possible by design of VSCode to activate a math Markdown plugin only when the document contains formulas.

Once installed, every Markdown plugin is activated whenever a Markdown file is previewed for the first time.

Markdown+Math extension addresses writing of student notes, scientific handouts or papers. Style guides for this recommend centered images and tables with centered captions. This is, what `vscode-mdmath.css` does.

`important` directives may be removed from there, which does not help much.

You have two possibilities:

1. Write a preview user css file, see https://code.visualstudio.com/Docs/languages/markdown#_using-your-own-css and overwrite mdmath style.
2. rename / remove `vscode-mdmath.css` completely

thanx
