### ISSUE TITLE
Inline mode is not working with vs code 1.54

### ISSUE THREAD

**Issue by chisuikafuku** [goessner/mdmath#108]
Hi,

I noticed this problem :
- Since vs code february update (1.54.3), inline mode is not working. For example the following: 

```
$1 +1 = 2$ is true.
```

does not format and still stay raw in preview mode. 

- When downgrading to vs code 1.53.2, everything is working well. 
- I tried both on Mac and windows.

**Comment by josealeixopc** [comment]
I am also having a similar issue. In VS Code 1.55.0, I am also experiencing **some** equations not being translated in the preview. More specifically:

1. When I open a **new** VS Code window with an `.md` containing equations and preview enabled, **everything works fine**.
2. I change to another tab with another `.md` file, which also changes the preview.
3. I come back to the original file and **some equations are now raw**.

I'm unsure if this is a VS Code problem or a problem from some dependency.

EDIT: Downgrading to VS Code 1.53.2, I verified that the problem is no longer there. Has there been some update to the preview mechanism?

**Comment by dominicwhite** [comment]
Having a similar issue with inline equations not rendering in Preview if they are inside an HTML table.

However my inline equations do render fine if they are elsewhere (e.g. part of a regular paragraph, or even inside a Markdown table).

E.g. the top table here is markdown, the second is HTML:
![image](https://user-images.githubusercontent.com/6020835/114593046-a8073880-9c59-11eb-968f-717027bcf440.png)

I am using VS Code 1.54.3. I have not tried downgrading.

**Comment by d0rf3n** [comment]
Still broken in 1.55, no highlighting of anything, also no autocompletions.

Since last commit is almost a year ago, I don't know of the chance of this getting updated?

Perhaps set as deprecated / remove if not actively being fixed. Thanks!

**Comment by goessner** [comment]
Can't reproduce ... everything seems to work ok with mdmath 2.6.
