### ISSUE TITLE
Extending VSCode's Builtin Markdown Preview

### ISSUE THREAD

**Issue by mjbvz** [goessner/mdmath#15]
Hey, I work on VSCode and am investigating allowing extensions to extend VSCode's builtin markdown preview. One big use case for this is adding math support.

Your extension already provides great support for markdown + math, so I wanted to reach out and see if you would be interested in exploring migrating to extend our builtin markdown preview instead of providing your own preview experience.

## Why
Users like being able to customize their markdown previews using extensions, but currently, this requires that each markdown extension implement its own preview. This results in an inconsistent markdown experience and is not scalable.

More concretely, extensions that use a custom markdown preview miss out on features we add to the builtin markdown preview, such as scroll synchronization, and also have missed out on the important security fixes we recently made around the markdown preview.

## How
The current proposal is to allow extensions to extend the built-in markdown preview. At a minimum, extensions would be able to register markdown-it plugins. Here's the current prototype of this: https://github.com/Microsoft/vscode/pull/22421 The `markdown-ext` extension included in the PR is for demonstration purposes only. It registers a markdown-it plugin that adds emoji support to our builtin markdown preview.

To support KaTeX, we will also have to support registering scripts and stylesheets to include in the preview as well.

If you were to move your extension to use the new plugin model, your extension would only be able to interact with the preview through these three extension points. At a minimum, this would require switching to use something like [`markdown-it-katex`](https://www.npmjs.com/package/markdown-it-katex).

## Todo
When you have a chance, let me know if this new extension point sounds like something you would be interested in exploring further. If so, take a look at the [current PR](https://github.com/Microsoft/vscode/pull/22421) and let me know if you have thoughts or concerns with where things stand. Specifically, I'd like to understand what APIs or features you'd need from our side to migrate your extension to this new model.

Thanks, and let me know if you have any questions.

**Comment by goessner** [comment]
Hi Matt,
in fact I was considering to suggest something like a markdown extension mechanism, as I also see the problem to write redundant code (scroll synchronisation .. you named it).

So I really like your plugin model proposal and am willing to try it out on basis of your emoji extension. I'm not sure at current, what's the exact difference between push and pull model. So I need to understand that first.

Defining the markdown extension in package.json and reusing/interacting with native previewer sounds very charming.

Regarding markdown-it-katex, I used that with my first version of mdmath and finally dropped it, as it was too restrictive and not easy to extend. I can't remember exactly what else it was leading me to that decision. 

What exactly must I do to try your emoji plugin out ?

Thanks

**Comment by mjbvz** [comment]
I've merge in the PR in an experimental state. The example emoji plugin has been split out to its own repo: https://github.com/mjbvz/vscode-markdown-emoji Follow the instructions using the latest insiders build to try it out

The difference between the push a pull model of extension contributions mainly boils down to who does the registration. In the pull model, each markdown preview extension declares that it can provide a set of contributions (plugins, scripts, or styles) and then our builtin markdown preview pulls these in when needed. In the push model,the markdown preview extensions go and register themselves with the markdown preview. The current api uses this model, although we still may switch back to the other model. Let me know if you have any feelings one way or the other.

Please check out the basic emoji plugin and let me know if you have any initial thoughts or concerns. Again, the API and behavior here is still being defined. Tomorrow I'm going to look into adding back support for registering styles and scripts to use in the preview

**Comment by mjbvz** [comment]
The api has been changed around and is now documented here: https://github.com/Microsoft/vscode/issues/22916 The actual implementation of this new api should be in the next VSCode insiders build. One other benefit of the new API is that other markdown preview implementations should be able to support these extension points if they wish to.

Here's a simple example of KaTeX support that works by registering a markdown-it plugin plus a stylesheet: https://github.com/mjbvz/vscode-markdown-katex

**Comment by goessner** [comment]
That looks all very promising. Unfortunately I won't have time to come back to mdmath and test your plugins until end of this week.

For now I would like to add some comments.

I first tried to modify/extend markdown-katex, but later gave up here due to enorm effort to integrate equation numbers as an example. Formula parsing does not fit very well with markdown-it's concept of *token streams*. So I tried to implement it alternatively using a small set of regular expressions, which worked surprisingly like a charm. This concept has several advantages. One of them is future implementation of alternate TeX/LaTeX equation delimiters according to several user requests. Those regular expressions might even be written to package.json for user configuration (some tests are required here of course).

That small regular expression set is applied immediatelly before markdown-it's render method call, think of ...
```
markdown = markdown.replace(rule1).replace(rule2) ... .replace(ruleN)
md.render(markdown)
```
So I would like to suggest a *pre-render / render / post-render* model API allowing some kind of Pre- and Postprocessing of the markdown string. Btw. think of the removal of the front matter stuff as another pre-rendering step. 

In fact I intend to do some kind of performance tests according to
* prerendering math formulas and add empty `<eq id="eqid"></eq>` to markdown
* intermediate storing formula markup in a list
* applying markdown-it rendering process
* finally injecting formula markup into corresponding `<eq id="eqid"></eq>` tags.

This might be valuable, as formula markup is still based on MathML, and so tends to get huge very fast.
Markdown-it rendering process isn't confronted with that big markup then and might perform all in all better. Implementing that concept does in fact require an additional *post-render* step.

Thanks

Stefan

ps.: I'm preferring JSON frontmatter style `{{{ ... }}}` instead of YAML style `--- ... ---` and I know I'm not alone. So I modified your frontmatter regular expression for mdmath to
```
/^\s*?[{-]{3}([\s\S]+?)[}-]{3}\s*?/
```
Just an idea. If you want, I will raise a separate issue for that.

**Comment by goessner** [comment]
Having revisited markdown-it token streams, I found an elegant way to handle equation numbers properly. Custom math delimiters should also work. Hope to have that markdown-it plugin as a first alpha version ready soon, to test it with your new API.

thanks

**Comment by goessner** [comment]
After having done a successful function proof using markdown-it token streams, I need to set work here to rest for 4 weeks from now on due to other priorities. Will continue in May then.

Thanks

**Comment by mjbvz** [comment]
@goessner Thanks for the update. The basic extension API is in VSCode 1.11 but will remain experimental until at least 1.12. Please let me know if I can help out with anything here too

**Comment by psukys** [comment]
Hello, any updates in this issue?

**Comment by goessner** [comment]
@mjbvz Have successfully mastered integration of new markdown-it extension in VSCode using your new API ... great.

More ... maybe some questions .. tomorrow then.

**Comment by goessner** [comment]
It works in fact as simple as in 
```js
exports.activate = function activate(context) {
    return {
        extendMarkdownIt: function(md) {
            return md.use(require('markdown-it-texmath'));
        }
    }
}
```
here using [markdown-it-texmath](https://github.com/goessner/markdown-it-texmath).
It's fun to see the markdown source now scrolling in sync with the preview window.

![grafik](https://cloud.githubusercontent.com/assets/4902746/26109829/bba21078-3a50-11e7-98b1-e07a140c8ccb.png)

* most tests are working.
* some minor formatting aspects are more strict than with mdmath, but nothing serious.
* even a very large math document of mine looks good.
* styling also works.
* I applause pssibility to have scripts in markdown preview ... which I do not need here.

**Comment by goessner** [comment]
@mjbvz: What would be the preferrable way to treat user settings/options for markdown extensions. So in order to set other math delimiters than the defaults, should they be set by 

`markdown.mdmath.delimiters`

or

`mdmath.delimiters`

What is the general recommendation for markdown extension developers ?

**Comment by mjbvz** [comment]
I'd stick to `mdmath.delimiter` and keep the settings in their own group. This makes is clearer where the settings are coming from

Exciting to see all the progress here. Is there anything on the VSCode side that is blocking you or that you have questions about?

**Comment by goessner** [comment]
@mjbvz: I am also excited about the fact, how lean `mdmath` finally has become due to your new API concept. All work is done now by [markdown-it-texmath](https://github.com/goessner/markdown-it-texmath), which is a pure and also lean `markdown-it` extension. So - as an additional benefit - that can be even used in pure `node.js` applications.

Now I have three questions:

* When will your API leave experimental status ?
* Can we expect some API changes then ?
* Can we expect HTML output from markdown in general ?

To the last point: Study work, thesis and research papers are usually required to be delivered as `*.pdf ` files. In order to restrict `mdmath` to its core competence (rendering TeX Math with vscode), I would like to have the compilation process of markdown to HTML format covered in future by another (native?) task - which not necessarily knows anything about math. Best way would be here to copy the HTML markup to the systems clipboard (s. [clipboardy](https://github.com/sindresorhus/clipboardy) or [copy-text-to-clipboard](https://github.com/sindresorhus/copy-text-to-clipboard) from the same author).
From HTML to PDF is an easy doable step then. 

Thanks

**Comment by shockwavemoto** [comment]
More concretely, extensions that use a custom markdown preview miss out on features we add to the builtin markdown preview, such as scroll synchronization, and also have missed out on the important security fixes we recently made around the markdown preview.most tests are working.
some minor formatting aspects are more strict than with mdmath, but nothing serious.
even a very large math document of mine looks good.
styling also works.
I applause pssibility to have scripts in markdown preview ... which I do not need here.
Having revisited markdown-it token streams, I found an elegant way to handle equation numbers properly. Custom math delimiters should also work. Hope to have that markdown-it plugin as a first alpha version ready soon, to test it with your new API.

**Comment by goessner** [comment]
@shockwavemoto: What does that patchwork of text fragments from previous posts mean ... ?

**Comment by mjbvz** [comment]
@goessner We've pushed the api change out for another month for further consider but hopefully will land it in June. For VS Code 1.13, I've also made a few minor tweaks to how styles are contributed. The change is documented here: https://github.com/Microsoft/vscode/issues/22916#issuecomment-303893496

The API may still change before the final release but I think that basic idea of extending the preview using commonmark plugins and stylesheet will remain the same.  

As for getting HTML output of the markdown preview, I can investigate this. There have been a few feature requests to add a `Save to html` command to the markdown preview in the past. I've been very hesitant to expose this functionality however because of the complexities involved (how to handle images and style sheets for example) and because it's then another complex area that the markdown extension would have to maintain and test

**Comment by goessner** [comment]
Current state:

Having integrated user selectable math delimiters in [markdown-it-texmath](https://github.com/goessner/markdown-it-texmath) now

* `dollars`: `$...$` for inline and `$$...$$` for display math.
* `brackets`: `\(...\)` for inline and `\[...\]` for display math.

Wiil do further tests and integrate  [markdown-it-texmath](https://github.com/goessner/markdown-it-texmath) into `mdmath` in June then ...

**Comment by mjbvz** [comment]
Markdown extensions are now enabled in the VSCode 1.15 insiders builds and should go out with the July release. Sorry for the delay, we had to handle some markdown issues that took priority over this.

The API has changed slightly, mainly in the names of the various markdown contribution points. You can find the current API documentation [here](https://github.com/Microsoft/vscode-docs/blob/vnext/docs/extensionAPI/api-markdown.md)

Please let me know if you run into any problems with the current API. There still isn't a way to get HTML out of the markdown preview without contributing a script but I can look into this if that's the main thing holding you back from adopting the markdown extension API

**Comment by goessner** [comment]
@mjbvz: These are good news. I am working with the new version of mdmath based on [markdown-it-texmath](https://github.com/goessner/markdown-it-texmath) all the time now and it works very stable.

There are only some few small restrictions due to markdown-it token streams, compared to the current version of mdmath. But I am - and I'm confident also users should be - able to live with it.

So I will wait for the July release and work in the API changes then. I won't have time to do anything for the next three weeks unfortunately,

Users won't accept authoring research documents, study work inside of vscode, when it is a closed shop. They expect export capabilities primarily as `*.pdf`, but they are also willing to live with `*.html` output.

So `mdmath` supports a poor man's export functionality at current, while copying the `html` to the systems clipboard. This is very easily done, when using [`clipboardy`](https://github.com/sindresorhus/clipboardy):
``` js
const cp = require('clipboardy');
// ...
cp.write(html).then(()=>vscode.window.showInformationMessage('Html copied to clipboard!'));
```
A very simple CSS is used for this. 
I would be very glad, if you look into this, as it is a quite critical feature here.

I am exporting to 'html' from a parallel script in `node.js` at current. You can have a look at my [recent article authored with new version of mdmath](http://s.goessner.net/article/CubicOfStationaryCurvature.html), if you like.

Thanks

**Comment by goessner** [comment]
`mdmath` is using  VSCode's builtin markdown preview now via markdown API with release 2.0.

Copying the html to the systems clipboard using `clipboardy` is supported further.

thanks
