### ISSUE TITLE
should ignore font packages in the math expression

### ISSUE THREAD

**Issue by shelper** [goessner/mdmath#35]
### Summary
some font package in math cannot be ignored
...

### Expected behavior
say if i have a math expression: \\$\boldsymbol{A}\\$, it is rendered by mdmath into \\\\boldsymbol **_A_** rather than just **_A_**

### Steps to reproduce

1. First step
2. Second step
3. Third step

### Code example

```md
Some markdown code ...

... with issues.
```

### Related links

* [Markdown+Math](https://github.com/goessner/mdmath)

### Environment

```text
     Operating system: ___
       VSCode version: ___
Markdown+Math version: ___
```

**Comment by goessner** [comment]
This is a question/issue concerning the KaTeX package itself. Please see (font) function support here:

https://github.com/Khan/KaTeX/wiki/Function-Support-in-KaTeX

You may raise an issue there.

Thanks

**Comment by RoyiAvital** [comment]
That's strange.

In mys sysem with the latest `mdmath` (2.1.0) on VS Code 1.19.2 the following:

`$$ {a}_{out} = {a}_{in} + \left( {y}_{out} - {y}_{in} \right) \boldsymbol{1} $$`

Won't work.
It says error regarding `\boldsymbol` while KaTeX states they support it.

Any idea?

**Comment by goessner** [comment]
Yes, I can verify this. It is seemingly supported with KaTeX, see ...

https://github.com/Khan/KaTeX/wiki/Function-Support-in-KaTeX

... but typed as an expression on KaTeX entry page ...

https://khan.github.io/KaTeX/

.. it generates an error also ... hmm.

Please raise an issue there.

**Comment by RoyiAvital** [comment]
Any chance to have an option to use MathJax?
KaTeX is just not good enough.

Also any chance not to enforce `$<LaTeX Code>$` but allow `$ <LaTeX Code> $` (Mind the Gap :-)).

I wonder if Visual Studio Code just have base HTML Template I can add MathJaX Script into.

Thank You.

**Comment by goessner** [comment]
`mdmath` serves me very well as it is. So I won't have time and interest to integrate and support MathJax.

If you want to start doing so, I can recommend to have a look at very simplistic solution

https://github.com/koehlma/vscode-markdown-math

Thanks

**Comment by RoyiAvital** [comment]
I have no idea how to write extensions.

I thought VS Code model is as follows:
1. There is a "Default HTML File"  
    It includes the standard header of an HTML file.
2. VS Code takes `md` file. Compiles it into HTML and insert it in the Body of the HTML File.

Now I was wondering what's that default HTML File as all needed is to add single line to it:

```
<script type="text/javascript" src="path-to-MathJax/MathJax.js">
    MathJax.Hub.Config({
        extensions: ["tex2jax.js"],
        jax: ["input/TeX", "output/HTML-CSS"],
        tex2jax: {
            inlineMath: [ ['$','$'], ["\\(","\\)"] ],
            displayMath: [ ['$$','$$'], ["\\[","\\]"] ],
        },
        "HTML-CSS": { availableFonts: ["TeX"] }
    });
</script>
```

Thank You.

**Comment by goessner** [comment]
welcome as a vscode extension developer.

Please realize, that vscode is not a browser, but an 'electron' application living in the `node.js` world while reusing the  `v8` browser kernel. There is more to this at current than simple 'CSS-JavaScript-HTML'  ... maybe some day ...

**Comment by RoyiAvital** [comment]
You say I was naive :-).

Well I got the idea from - https://stackoverflow.com/a/42501557/195787.

KaTeX lacks so many environments that MathJaX has.
Even basic one like `align`.  
Not to mention all macros.

Moreover, the Pandoc style of brackets makes code very hard to read in my opinion.  
Since I'm aware of writing LaTeX I will be aware of cases with `$` hence I'd like option to make a valid Inline Math with `$ <LaTeX Code> $`.

Anyhow,
Thank you for this project.
It's really great and effective.

**Comment by goessner** [comment]
No, this was not my intention :-)

But having a quick look at  https://stackoverflow.com/a/42501557/195787, now I see ...

It's completely different, to integrate KaTeX or MathJax into vscode's markdown previewer from the quite simple workflow with compiling a markdown document/file to HTML. You could achive this - as suggested - via

https://code.visualstudio.com/Docs/languages/markdown#_compiling-markdown-into-html

or by `mdmath` feature of 'exporting HTML code'.

https://github.com/goessner/mdmath

With this HTML document available you can then integrate your `<script>` code above quite easily and substitute so KaTex by MathJax.

Thanks

**Comment by RoyiAvital** [comment]
Yea,
Well I thought that the preview in VS Code is based on Template HTML page where the "Compiled" MarkDown is injected into it in its "Body" element.

Then all I needed is yo locate this template and add the script.
Naive :-).

Anyhow, I still wish one day you will have time to integrate MathJaX and it will be built in.

Also I see that now KaTeX will fix the issue I found, so something good is already done.

Thank You.

**Comment by edemaine** [comment]
Hi folks!  A KaTeX developer here.  I definitely got interested in KaTeX because it is so easy to integrate into existing web systems as part of the rendering pipeline, including for example server-side rendering, whereas MathJax requires the browser to dynamically adjust the rendering (and is 10x+ slower too).  We are constantly adding new features, fixing bugs, etc. in KaTeX.  If there's something important that you're missing, please [open an issue](https://github.com/Khan/KaTeX/issues) (or post on an existing issue if it's there).

@RoyiAvital and @goessner: Yes, `\boldsymbol` was added in v0.9.0-beta (as well as v0.9.0, just released).  I believe `mdmath` is currently using 0.8.2, so a simple upgrade should add support for `\boldsymbol`.  (We haven't even upgraded our own [demo site](https://khan.github.io/KaTeX/) yet, which is why it doesn't work there either.  Sorry for the confusion!  Should be fixed soon.)

Let me know if you'd like a PR for mdmath to upgrade KaTeX.

**Comment by RoyiAvital** [comment]
@edemaine , 
I'm already participating in KaTeX issues.  
The main thing is lack of support of environments and numbering.

But the important thing is KaTeX is a great project.
Truly a significant contribution to Scientific writing.

**Comment by edemaine** [comment]
I forgot to mention specifically about `align`: there is a workaround, to use `$$\begin{aligned} ... \end{aligned}$$`.  It would be easy to add support to mdmath for mapping `\begin{align} ... \end{align}` to exactly this, as I did [here](https://github.com/edemaine/coauthor/blob/master/lib/formats.coffee#L28-L30).  It's a bit difficult to add to KaTeX directly, because it's only given the content *inside* a math block, and `$$\begin{align} ... \end{align}$$` doesn't make sense.

Regarding numbering: I assume you mean [equation numbering](https://github.com/Khan/KaTeX/issues/350]) and/or [`\tag` support](https://github.com/Khan/KaTeX/issues/899)?  I did some work on the latter, and have some questions that could use feedback if you'd like to help think about how to render equation numbers.

Let us know what other environments you're missing that you consider a priority for KaTeX!

**Comment by goessner** [comment]
.. ok .. I will update mdmath in using katex@0.9.0 then in near future.

@edemaine, thanks for your offer .. no need for or PR here .. and thanks for your turbo math engine.

**Comment by goessner** [comment]
@edemaine,
I am already aware of `\begin{aligned} ... \end{aligned}` and use it when I need it. I am very interested in any success regarding equation numbering. As you may have noticed, I have implemented an interims poor man's equation numbering with mdmath.

It all in all works quite well, as you might see in this article from mine authored with mdmath

https://www.researchgate.net/publication/318661368_The_Planar_Euler-Savary_Equation_in_Vectorial_Notation

thanks

**Comment by RoyiAvital** [comment]
@goessner ,
How did you create the Figure Caption beneath each figure?

**Comment by goessner** [comment]
simply by using the fact that markdown allows embedded html ...
```
<figure>
  <img src="img.png">
  <figcaption>Fig.1: kinematics</figcaption>
</figure>
```
