### ISSUE TITLE
Math rendering in HTML but not in preview (unix)

### ISSUE THREAD

**Issue by tomMoral** [goessner/mdmath#9]
### Summary

The preview does not render math in Vscode but an HTML export works.

![error](https://cloud.githubusercontent.com/assets/3321081/23044076/a52dc168-f46c-11e6-964d-db9c7a6b18fc.png)

### Environment

```text
Operating system: archlinux
VSCode version: 1.9.1
Shell 1.4.6
Renderer 53.0.2785.143
Node: 6.5.0
Markdown+Math version: 1.1.0
```

**Comment by goessner** [comment]
Are you sure, you used <kbd>CTRL+Shift+.</kbd> instead of <kbd>CTRL+Shift+V</kbd> for viewing ... as your headline should show "Preview: subgaussian.md" instead of "Preview 'subgaussian.md'" then.

Also note, that inline math should not start or end with whitespace ... so please write $X$ instead of $ X $.

Unfortunately I am not able to test with your operating system.

Thanks

**Comment by tomMoral** [comment]
Okay it worked. Sorry, I was sure I tried it.
Thanks for the quick answer!
